### ISSUE TITLE
Multus: error in invoke Delegate add - "sriov", invalid argument

### ISSUE THREAD

**Issue by hymgg** [intel/sriov-cni#79] opened 2019-06-03 23:28 UTC
Just started using the multus-cni, sriov-cni, sriov-device-plugin.

Multus has 2 delegates, Calico on default network, sriov on another.

sriov-device-plugin could see the VFs, "intel.com/sriov_net_A": "16"

$ kubectl get node mtx-huawei2-bld05 -o json | jq '.status.allocatable'
{
  "cpu": "64",
  "ephemeral-storage": "48294789041",
  "hugepages-1Gi": "0",
  "hugepages-2Mi": "0",
  "intel.com/sriov_net_A": "16",
  "intel.com/sriov_net_B": "0",
  "memory": "196389160Ki",
  "pods": "110"
}

multus conf:

# cat 05-multus.conf
{
  "name": "multus-cni-network",
  "type": "multus",
  "delegates": [
    {
      "name": "k8s-pod-network",
      "cniVersion": "0.3.0",
      "plugins": [
        {
          "type": "calico",
          "log_level": "info",
          "datastore_type": "kubernetes",
          "nodename": "mtx-huawei2-bld05",
          "mtu": 1440,
          "ipam": {
            "type": "host-local",
            "subnet": "usePodCidr"
          },
          "policy": {
              "type": "k8s"
          },
          "kubernetes": {
              "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
          }
        },
        {
          "type": "portmap",
          "snat": true,
          "capabilities": {"portMappings": true}
        }
      ]
    }
  ],
  "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig"
}

sriov crd:

# cat sriov-nad-4.yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-net-4
  namespace: mtx-test10
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/sriov_net_A
spec:
  config: '{
  "type": "sriov",
  "name": "sriov-network-4",
  "ipam": {
    "type": "host-local",
    "subnet": "10.64.217.0/24",
    "routes": [{
      "dst": "0.0.0.0/0"
    }],
    "gateway": "10.64.217.1"
  }
}'

sriov-device-plugin resources:

# cat configMap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [{
                "resourceName": "sriov_net_A",
                "selectors": {
                    "vendors": ["14e4"],
                    "devices": ["16af"],
                    "drivers": ["bnx2x"],
                    "pfNames": ["eno31"]
                }
            }
        ]
    }

pod yaml:

# cat pod-tc1.yaml
apiVersion: v1
kind: Pod
metadata:
  name: testpod1
  namespace: mtx-test10
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-net-4
spec:
  containers:
  - name: appcntr1 
    image: centos/tools 
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    resources:
      requests:
        intel.com/sriov_net_A: '1' 
      limits:
        intel.com/sriov_net_A: '1'
  nodeName: mtx-huawei2-bld05

$ kubectl describe pod testpod1 -n mtx-test10
...
...
  Warning  FailedCreatePodSandBox  3m28s (x296 over 42m)  kubelet, mtx-huawei2-bld05  (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "1bc793ca392c9745f0ce6352f01bd86bb509567308416b09e02ad9a0011ca70c" network for pod "testpod1": NetworkPlugin cni failed to set up pod "testpod1_mtx-test10" network: Multus: Err adding pod to network "sriov-network-4": Multus: error in invoke Delegate add - "sriov": failed to setup netlink device enp59s4f1 "invalid argument", failed to clean up sandbox container "1bc793ca392c9745f0ce6352f01bd86bb509567308416b09e02ad9a0011ca70c" network for pod "testpod1": NetworkPlugin cni failed to teardown pod "testpod1_mtx-test10" network: Multus: error in invoke Delegate del - "sriov": failed to lookup vf device "net1": Link not found]

/var/log/messages reported:
do-change-link[82]: failure changing link: failure 22 (Invalid argument)

Jun  3 15:37:07 mtx-huawei2-bld05 kernel: [444586.545494] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
Jun  3 15:37:07 mtx-huawei2-bld05 kubelet[82494]: 2019-06-03 15:37:07.824 [INFO][24437] network.go 380: Disabling IPv4 forwarding ContainerID="fa008dddb917c7d21b86f52555b1641dd03d6f08404af0032c2b48a4d8988389" Namespace="mtx-test10" Pod="testpod1" WorkloadEndpoint="mtx--huawei2--bld05-k8s-testpod1-eth0"
Jun  3 15:37:07 mtx-huawei2-bld05 kernel: [444586.569626] IPv6: ADDRCONF(NETDEV_UP): cali38aee219176: link is not ready
Jun  3 15:37:07 mtx-huawei2-bld05 kubelet[82494]: 2019-06-03 15:37:07.848 [INFO][24437] k8s.go 392: Added Mac, interface name, and active container ID to endpoint ContainerID="fa008dddb917c7d21b86f52555b1641dd03d6f08404af0032c2b48a4d8988389" Namespace="mtx-test10" Pod="testpod1" WorkloadEndpoint="mtx--huawei2--bld05-k8s-testpod1-eth0" endpoint=&v3.WorkloadEndpoint{TypeMeta:v1.TypeMeta{Kind:"WorkloadEndpoint", APIVersion:"projectcalico.org/v3"}, ObjectMeta:v1.ObjectMeta{Name:"mtx--huawei2--bld05-k8s-testpod1-eth0", GenerateName:"", Namespace:"mtx-test10", SelfLink:"", UID:"1ab4bff0-8650-11e9-bd09-14579fa1adef", ResourceVersion:"9279897", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63695198221, loc:(*time.Location)(0x1ede720)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"projectcalico.org/serviceaccount":"default", "projectcalico.org/namespace":"mtx-test10", "projectcalico.org/orchestrator":"k8s"}, Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:v3.WorkloadEndpointSpec{Orchestrator:"k8s", Workload:"", Node:"mtx-huawei2-bld05", ContainerID:"fa008dddb917c7d21b86f52555b1641dd03d6f08404af0032c2b48a4d8988389", Pod:"testpod1", Endpoint:"eth0", IPNetworks:[]string{"10.100.11.135/32"}, IPNATs:[]v3.IPNAT(nil), IPv4Gateway:"", IPv6Gateway:"", Profiles:[]string{"kns.mtx-test10", "ksa.mtx-test10.default"}, InterfaceName:"cali38aee219176", MAC:"36:da:3a:16:f9:62", Ports:[]v3.EndpointPort(nil)}}
Jun  3 15:37:07 mtx-huawei2-bld05 kernel: [444586.570825] IPv6: ADDRCONF(NETDEV_CHANGE): cali38aee219176: link becomes ready
Jun  3 15:37:07 mtx-huawei2-bld05 kernel: [444586.571065] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
Jun  3 15:37:07 mtx-huawei2-bld05 kubelet[82494]: 2019-06-03 15:37:07.850 [INFO][24437] k8s.go 424: Wrote updated endpoint to datastore ContainerID="fa008dddb917c7d21b86f52555b1641dd03d6f08404af0032c2b48a4d8988389" Namespace="mtx-test10" Pod="testpod1" WorkloadEndpoint="mtx--huawei2--bld05-k8s-testpod1-eth0"
Jun  3 15:37:07 mtx-huawei2-bld05 NetworkManager[28813]: <info>  [1559601427.8607] device (cali38aee219176): carrier: link connected
Jun  3 15:37:07 mtx-huawei2-bld05 NetworkManager[28813]: <info>  [1559601427.8909] manager: (cali38aee219176): new Veth device (/org/freedesktop/NetworkManager/Devices/2925)
Jun  3 15:37:07 mtx-huawei2-bld05 NetworkManager[28813]: <info>  [1559601427.8990] device (enp59s4f1): state change: disconnected -> unmanaged (reason 'removed', sys-iface-state: 'removed')
Jun  3 15:37:07 mtx-huawei2-bld05 NetworkManager[28813]: <info>  [1559601427.9197] manager: (dev82): new Ethernet device (/org/freedesktop/NetworkManager/Devices/2926)
Jun  3 15:37:07 mtx-huawei2-bld05 NetworkManager[28813]: <info>  [1559601427.9321] device (enp59s4f1): state change: unmanaged -> unavailable (reason 'managed', sys-iface-state: 'external')
Jun  3 15:37:07 mtx-huawei2-bld05 kernel: [444586.655546] IPv6: ADDRCONF(NETDEV_UP): enp59s4f1: link is not ready
Jun  3 15:37:07 mtx-huawei2-bld05 NetworkManager[28813]: <warn>  [1559601427.9372] platform-linux: do-change-link[82]: failure changing link: failure 22 (Invalid argument)
Jun  3 15:37:07 mtx-huawei2-bld05 NetworkManager[28813]: <info>  [1559601427.9384] device (enp59s4f1): state change: unavailable -> disconnected (reason 'none', sys-iface-state: 'managed')
Jun  3 15:37:07 mtx-huawei2-bld05 kernel: [444586.660476] IPv6: ADDRCONF(NETDEV_UP): enp59s4f1: link is not ready
Jun  3 15:37:07 mtx-huawei2-bld05 kubelet[82494]: 2019-06-03 15:37:07.982 [INFO][24537] calico.go 442: Extracted identifiers ContainerID="fa008dddb917c7d21b86f52555b1641dd03d6f08404af0032c2b48a4d8988389" Node="mtx-huawei2-bld05" Orchestrator="k8s" WorkloadEndpoint="mtx--huawei2--bld05-k8s-testpod1-eth0"
Jun  3 15:37:07 mtx-huawei2-bld05 kubelet[82494]: 2019-06-03 15:37:07.987 [WARNING][24537] workloadendpoint.go 70: Operation Delete is not supported on WorkloadEndpoint type

**Comment by zshi-redhat** [comment] 2019-06-04 00:55
From the log message, it seems that device `enp59s4f1` is disconnected and changing of link state failed:
```
Jun 3 15:37:07 mtx-huawei2-bld05 NetworkManager[28813]: [1559601427.9372] platform-linux: do-change-link[82]: failure changing link: failure 22 (Invalid argument)
Jun 3 15:37:07 mtx-huawei2-bld05 NetworkManager[28813]: [1559601427.9384] device (enp59s4f1): state change: unavailable -> disconnected (reason 'none', sys-iface-state: 'managed')
```
Perhaps check the link state?
If that's not the cause, you might want to [enable Multus debug log](https://github.com/intel/multus-cni/blob/master/doc/configuration.md#logging) which may contain details of sriov-cni code failure.

**Comment by hymgg** [comment] 2019-06-05 00:11
Thank you for the followup.

Thought the state change to disconnected was a result of the failed do-change-link? wonder why it failed...

Enabled multus debug log, please take a look
[multus.log](https://github.com/intel/sriov-cni/files/3254942/multus.log)

Can't figure out much besides the key message:
2019-06-04T16:59:54-07:00 [error] Multus: error in invoke Delegate add - "sriov": failed to setup netlink device enp59s3f5 "invalid argument"

**Comment by zshi-redhat** [comment] 2019-06-05 00:35
> Thank you for the followup.
> 
> Thought the state change to disconnected was a result of the failed do-change-link? wonder why it failed...
> 
> Enabled multus debug log, please take a look
> [multus.log](https://github.com/intel/sriov-cni/files/3254942/multus.log)
> 
> Can't figure out much besides the key message:
> 2019-06-04T16:59:54-07:00 [error] Multus: error in invoke Delegate add - "sriov": failed to setup netlink device enp59s3f5 "invalid argument"

Which `sriov-cni` version are you using? From the log message, it looks like not the latest master, but a release branch?
When vf device is passed to sriov-cni, it tries to first set the link state up and then move the interface to pod namespace; I guess the error happened when netlink library is called to set the VF link up. could you please check if you can set the VF(enp59s3f5) up with `ip` cmd?
Would you please also make sure that PF device is up ? I don't have a bnx2x card, not sure which mode VF is used to follow PF link state, better to check it's not auto and PF is not down.

**Comment by hymgg** [comment] 2019-06-05 08:02
1.) The image is as defined in sriov-cni-daemonset.yaml, it's 6-month old but seems to be the latest still. Is there a place to get a better one?

# docker images|grep sriov-cni
nfvpe/sriov-cni                             latest                   3ceeb1e50924        6 months ago        263MB

# docker pull nfvpe/sriov-cni
Using default tag: latest
latest: Pulling from nfvpe/sriov-cni
Digest: sha256:09dc819e76527d0530a90672016f0f798d961e9f847b4aea719b7b7c56aaa8fd
Status: Image is up to date for nfvpe/sriov-cni:latest

2.) ip addr add works on the failed VF. Is it possible to find out what commands were executed from sriov-cni so we could repeat and see which one resulted in "Invalid argument"?

[root@mtx-huawei2-bld05 net.d]# ip addr show dev enp59s3f5
51: enp59s3f5: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 1a:11:c0:10:3d:23 brd ff:ff:ff:ff:ff:ff

[root@mtx-huawei2-bld05 net.d]# ip addr add 192.168.1.1/24 dev enp59s3f5

[root@mtx-huawei2-bld05 net.d]# ip addr show dev enp59s3f5
51: enp59s3f5: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 1a:11:c0:10:3d:23 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.1/24 scope global enp59s3f5
       valid_lft forever preferred_lft forever


3.) Regarding link state, didn't play with it, guess auto is default, the PF is an active slave of a bond, should it be set to enable or something?

[root@mtx-huawei2-bld05 net.d]# ip link show eno31
6: eno31: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond1 state UP mode DEFAULT group default qlen 1000
    link/ether 58:f9:87:78:be:94 brd ff:ff:ff:ff:ff:ff
    vf 0 MAC 00:00:00:00:00:00, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
    vf 1 MAC 00:00:00:00:00:00, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
    vf 2 MAC 00:00:00:00:00:00, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
    vf 3 MAC 00:00:00:00:00:00, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
    vf 4 MAC 00:00:00:00:00:00, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
    vf 5 MAC 00:00:00:00:00:00, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
    vf 6 MAC 00:00:00:00:00:00, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
    vf 7 MAC 00:00:00:00:00:00, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
    vf 8 MAC 00:00:00:00:00:00, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
    vf 9 MAC 00:00:00:00:00:00, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
    vf 10 MAC 00:00:00:00:00:00, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
    vf 11 MAC 00:00:00:00:00:00, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
    vf 12 MAC 00:00:00:00:00:00, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
    vf 13 MAC 00:00:00:00:00:00, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
    vf 14 MAC 00:00:00:00:00:00, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
    vf 15 MAC 00:00:00:00:00:00, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto

4.) Another observation, after machine reboots, the 16 VFs are all with "NO-CARRIER,BROADCAST,MULTICAST,UP"

[root@mtx-huawei2-bld05 ~]# ip a |grep enp59s3
27: enp59s3: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
30: enp59s3f1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
33: enp59s3f2: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
37: enp59s3f3: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
43: enp59s3f4: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
49: enp59s3f5: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
57: enp59s3f6: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
65: enp59s3f7: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
[root@mtx-huawei2-bld05 ~]# ip a |grep enp59s4
74: enp59s4: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
82: enp59s4f1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
90: enp59s4f2: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
95: enp59s4f3: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
102: enp59s4f4: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
108: enp59s4f5: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
116: enp59s4f6: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
124: enp59s4f7: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000

After a failed attempt to start a pod, one of the VFs -- probably the chosen one for the pod -- will come back in state:
102: enp59s4f4: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000


Thanks.  -Jessica

**Comment by zshi-redhat** [comment] 2019-06-05 08:23
> 1.) The image is as defined in sriov-cni-daemonset.yaml, it's 6-month old but seems to be the latest still. Is there a place to get a better one?

Yes, it seems an old one, maybe due to the image under `nfvpe/sriov-cni` is not updated properly when new PR merged. Anyway, you can build the sriov-cni binary(execute `make build`) from latest code and copy `build/sriov` to `/opt/cni/bin/` directory, then `Multus` will be able to use the newly built sriov-cni binary. Then we can capture the new log message and see where the error occurs.

> 
> # docker images|grep sriov-cni
> nfvpe/sriov-cni latest 3ceeb1e50924 6 months ago 263MB
> 
> # docker pull nfvpe/sriov-cni
> Using default tag: latest
> latest: Pulling from nfvpe/sriov-cni
> Digest: sha256:09dc819e76527d0530a90672016f0f798d961e9f847b4aea719b7b7c56aaa8fd
> Status: Image is up to date for nfvpe/sriov-cni:latest
> 
> 2.) ip addr add works on the failed VF. Is it possible to find out what commands were executed from sriov-cni so we could repeat and see which one resulted in "Invalid argument"?

From previous log message, the error happened at [here](https://github.com/intel/sriov-cni/blob/release-v1/sriov/sriov.go#L353); so we are using `github.com/vishvananda/netlink` library to set up the link state, the exact function called is [LinkSetUp](https://github.com/vishvananda/netlink/blob/master/link_linux.go#L274).


> 
> [root@mtx-huawei2-bld05 net.d]# ip addr show dev enp59s3f5
> 51: enp59s3f5: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
> link/ether 1a:11:c0:10:3d:23 brd ff:ff:ff:ff:ff:ff
> 
> [root@mtx-huawei2-bld05 net.d]# ip addr add 192.168.1.1/24 dev enp59s3f5
> 
> [root@mtx-huawei2-bld05 net.d]# ip addr show dev enp59s3f5
> 51: enp59s3f5: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
> link/ether 1a:11:c0:10:3d:23 brd ff:ff:ff:ff:ff:ff
> inet 192.168.1.1/24 scope global enp59s3f5
> valid_lft forever preferred_lft forever
> 
> 3.) Regarding link state, didn't play with it, guess auto is default, the PF is an active slave of a bond, should it be set to enable or something?

I didn't try with PF enslaved in a bond interface, would it be possible to try removing PF from bond? just to isolated the problem.

> 
> [root@mtx-huawei2-bld05 net.d]# ip link show eno31
> 6: eno31: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond1 state UP mode DEFAULT group default qlen 1000
> link/ether 58:f9:87:78:be:94 brd ff:ff:ff:ff:ff:ff
> vf 0 MAC 00:00:00:00:00:00, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
> vf 1 MAC 00:00:00:00:00:00, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
> vf 2 MAC 00:00:00:00:00:00, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
> vf 3 MAC 00:00:00:00:00:00, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
> vf 4 MAC 00:00:00:00:00:00, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
> vf 5 MAC 00:00:00:00:00:00, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
> vf 6 MAC 00:00:00:00:00:00, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
> vf 7 MAC 00:00:00:00:00:00, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
> vf 8 MAC 00:00:00:00:00:00, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
> vf 9 MAC 00:00:00:00:00:00, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
> vf 10 MAC 00:00:00:00:00:00, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
> vf 11 MAC 00:00:00:00:00:00, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
> vf 12 MAC 00:00:00:00:00:00, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
> vf 13 MAC 00:00:00:00:00:00, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
> vf 14 MAC 00:00:00:00:00:00, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
> vf 15 MAC 00:00:00:00:00:00, tx rate 10000 (Mbps), max_tx_rate 10000Mbps, spoof checking on, link-state auto
> 
> 4.) Another observation, after machine reboots, the 16 VFs are all with "NO-CARRIER,BROADCAST,MULTICAST,UP"
> 
> [root@mtx-huawei2-bld05 ~]# ip a |grep enp59s3
> 27: enp59s3: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
> 30: enp59s3f1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
> 33: enp59s3f2: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
> 37: enp59s3f3: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
> 43: enp59s3f4: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
> 49: enp59s3f5: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
> 57: enp59s3f6: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
> 65: enp59s3f7: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
> [root@mtx-huawei2-bld05 ~]# ip a |grep enp59s4
> 74: enp59s4: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
> 82: enp59s4f1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
> 90: enp59s4f2: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
> 95: enp59s4f3: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
> 102: enp59s4f4: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
> 108: enp59s4f5: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
> 116: enp59s4f6: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
> 124: enp59s4f7: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
> 
> After a failed attempt to start a pod, one of the VFs -- probably the chosen one for the pod -- will come back in state:
> 102: enp59s4f4: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
> 
> Thanks. -Jessica

**Comment by hymgg** [comment] 2019-06-07 16:48
Built sriov from latest code, the messages are a bit different, but essentially the same result.

The pointers to code helped narrow down the issue, assuming the steps in function SetupVF are equivalent to running ip link commands, I could run ip link set xxx down, then up, on physical NIC, but not on VFs.

Following up with lab manager and redhat on this... will update

[root@mtx-huawei2-bld05 log]# ip link |grep eno51
7: eno51: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond1 state UP mode DEFAULT group default qlen 1000
[root@mtx-huawei2-bld05 log]# ip link set eno51 down
[root@mtx-huawei2-bld05 log]# ip link |grep eno51
7: eno51: <BROADCAST,MULTICAST,SLAVE> mtu 1500 qdisc mq master bond1 state DOWN mode DEFAULT group default qlen 1000
[root@mtx-huawei2-bld05 log]# ip link set eno51 up
[root@mtx-huawei2-bld05 log]# ip link |grep eno51
7: eno51: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond1 state UP mode DEFAULT group default qlen 1000

[root@mtx-huawei2-bld05 log]# ip a |grep enp59s3f1
30: enp59s3f1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
[root@mtx-huawei2-bld05 log]# ip link set enp59s3f1 down
[root@mtx-huawei2-bld05 log]# ip a |grep enp59s3f1
30: enp59s3f1: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
[root@mtx-huawei2-bld05 log]# ip link set enp59s3f1 up
RTNETLINK answers: Invalid argument

Thanks.  -Jessica

**Comment by hymgg** [comment] 2019-06-07 17:13
Attached multus.log from new code
[multus.log](https://github.com/intel/sriov-cni/files/3266950/multus.log)

2019-06-06T12:12:18-07:00 [error] Multus: error in invoke Delegate add - "sriov": failed to set up pod interface "net1" from the device "eno31": error setting up interface in container namespace: "error bringing interface up in container ns: \"invalid argument\""

That's how I went to SetupVF

**Comment by zshi-redhat** [comment] 2019-06-10 01:08
> Built sriov from latest code, the messages are a bit different, but essentially the same result.
> 
> The pointers to code helped narrow down the issue, assuming the steps in function SetupVF are equivalent to running ip link commands, I could run ip link set xxx down, then up, on physical NIC, but not on VFs.

Yes, it should be equivalent to running ip cmd, as both are using netlink to configure link state.
The new log message shows that it errors at the same function `[LinkSetUp](https://github.com/intel/sriov-cni/blob/master/pkg/sriov/sriov.go#L138)`, my guess is that the vf driver doesn't support the config option?

> 
> Following up with lab manager and redhat on this... will update
> 
> [root@mtx-huawei2-bld05 log]# ip link |grep eno51
> 7: eno51: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond1 state UP mode DEFAULT group default qlen 1000
> [root@mtx-huawei2-bld05 log]# ip link set eno51 down
> [root@mtx-huawei2-bld05 log]# ip link |grep eno51
> 7: eno51: <BROADCAST,MULTICAST,SLAVE> mtu 1500 qdisc mq master bond1 state DOWN mode DEFAULT group default qlen 1000
> [root@mtx-huawei2-bld05 log]# ip link set eno51 up
> [root@mtx-huawei2-bld05 log]# ip link |grep eno51
> 7: eno51: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond1 state UP mode DEFAULT group default qlen 1000
> 
> [root@mtx-huawei2-bld05 log]# ip a |grep enp59s3f1
> 30: enp59s3f1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
> [root@mtx-huawei2-bld05 log]# ip link set enp59s3f1 down
> [root@mtx-huawei2-bld05 log]# ip a |grep enp59s3f1
> 30: enp59s3f1: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
> [root@mtx-huawei2-bld05 log]# ip link set enp59s3f1 up
> RTNETLINK answers: Invalid argument
> 
> Thanks. -Jessica

**Comment by hymgg** [comment] 2019-06-10 17:48
Yes eno51 is a physical nic, ip link commands worked, enp59s3f1 is a VF, failed, will come back.

Thanks.  -Jessica

**Comment by ahalim-intel** [comment] 2019-06-13 08:31
@hymgg Thank you for reporting this issue. We have recently applied few changes to update the docker image. The original issue described here should be gone now. Feel free to open this issue if you are still experiencing same problem.

**Closed by ahalim-intel** 2019-06-13 08:31 UTC
