### ISSUE TITLE
Plugin Returns Error

### ISSUE THREAD

**Issue by cliffburdick** [intel/sriov-cni#72] opened 2019-03-09 00:05 UTC
Hi, I'm trying to get the SR-IOV plugin working with multus, and no luck so far. When I deploy, I get the error:

```
  Warning  FailedCreatePodSandBox  73s   kubelet, s011  Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "af8b92d1581875f0eedfce9773867127d5db4a204dedf075b5006a009fc9b8e9" network for pod "ut-cburdick-b6f192": NetworkPlugin cni failed to set up pod "ut-cburdick-b6f192_default" network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input, failed to clean up sandbox container "af8b92d1581875f0eedfce9773867127d5db4a204dedf075b5006a009fc9b8e9" network for pod "ut-cburdick-b6f192": NetworkPlugin cni failed to teardown pod "ut-cburdick-b6f192_default" network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input]
```

My network attachment definition looks like this:
```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: host-device-conf1
spec:
  config: '{
            "cniVersion": "0.2.0",
            "name": "mynet1",
            "type": "sriov",
            "if0": "ens1f0",
            "l2enable": true
        }'
```

I'm running multus:snapshot as of today, and SR-IOV version 1.0.0 of the plugin. I also tried the master branch with "master" instead of "if0" with the same error.

My goal is to eventually use DPDK on a Mellanox card across pods. I intentionally didn't use the DPDK section since I don't want the driver to be loaded (Mellanox doesn't need that), but I'm not sure if that's correct.

**Comment by zshi-redhat** [comment] 2019-03-11 01:40
> Hi, I'm trying to get the SR-IOV plugin working with multus, and no luck so far. When I deploy, I get the error:
> 
> ```
>   Warning  FailedCreatePodSandBox  73s   kubelet, s011  Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "af8b92d1581875f0eedfce9773867127d5db4a204dedf075b5006a009fc9b8e9" network for pod "ut-cburdick-b6f192": NetworkPlugin cni failed to set up pod "ut-cburdick-b6f192_default" network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input, failed to clean up sandbox container "af8b92d1581875f0eedfce9773867127d5db4a204dedf075b5006a009fc9b8e9" network for pod "ut-cburdick-b6f192": NetworkPlugin cni failed to teardown pod "ut-cburdick-b6f192_default" network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input]

This looks like an error from Multus instead of SR-IOV plugin, I hit the same by building Multus from latest master. @s1061123,  do you know what's the problem? I switched to an old commit "9b41f7635deb6cf11beb02bbce530435640cd6a2" and it works.

> ```
> My network attachment definition looks like this:
> 
> ```
> apiVersion: "k8s.cni.cncf.io/v1"
> kind: NetworkAttachmentDefinition
> metadata:
>   name: host-device-conf1
> spec:
>   config: '{
>             "cniVersion": "0.2.0",
>             "name": "mynet1",
>             "type": "sriov",
>             "if0": "ens1f0",
>             "l2enable": true
>         }'
> ```
> I'm running multus:snapshot as of today, and SR-IOV version 1.0.0 of the plugin. I also tried the master branch with "master" instead of "if0" with the same error.
> 
> My goal is to eventually use DPDK on a Mellanox card across pods. I intentionally didn't use the DPDK section since I don't want the driver to be loaded (Mellanox doesn't need that), but I'm not sure if that's correct.

**Comment by cliffburdick** [comment] 2019-03-11 18:01
@zshi-redhat can you point to which version of SR-IOV you're using? I tried with that multus build and am getting a new error with the SR-IOV plugin:

Warning  FailedCreatePodSandBox  67s   kubelet, b011  Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "5148e77c70d8d769a5c0b1c10b4e5f15e934ba2e14c2d29e4c66ceb7ece244a9" network for pod "ut-cburdick-b6f192": NetworkPlugin cni failed to set up pod "ut-cburdick-b6f192_default" network: Multus: Err adding pod to network "cni0": Multus: error in invoke Conflist add - "cni0": error in getting result from AddNetworkList: failed to request 1 IPv4 addresses. IPAM allocated only 0, failed to clean up sandbox container "5148e77c70d8d769a5c0b1c10b4e5f15e934ba2e14c2d29e4c66ceb7ece244a9" network for pod "ut-cburdick-b6f192": NetworkPlugin cni failed to teardown pod "ut-cburdick-b6f192_default" network: Multus: error in invoke Delegate del - "sriov": unable to get shared PF device: Link not found]

**Comment by zshi-redhat** [comment] 2019-03-12 00:20
> unable to get shared PF device

To test DPDK, please use master branches for both SR-IOV CNI and [SR-IOV Device Plugin](https://github.com/intel/sriov-network-device-plugin); you may also want to remove``if0`` in net-attach-def 
as it is not supported in SR-IOV CNI master branch. There are detailed instructions in SR-IOV Device Plugin Readme file on how to setup the config and environment.

**Comment by cliffburdick** [comment] 2019-03-12 00:23
Thanks @zshi-redhat. Is the commit for multus the one you'd recommend?

**Comment by zshi-redhat** [comment] 2019-03-12 00:26
> Thanks @zshi-redhat. Is the commit for multus the one you'd recommend?

It worked in my environment with that commit yesterday, didn't investigate on what exact the problem is with latest master of Multus, I guess you can use that commit to spin up the env quickly.

**Comment by cliffburdick** [comment] 2019-03-13 16:58
@zshi-redhat we got it working with the latest SR-IOV + that multus commit, Thanks for pointing that out.

**Comment by zshi-redhat** [comment] 2019-03-25 13:42
This should be fixed in multus [PR](https://github.com/intel/multus-cni/pull/283), closing issue.

**Closed by zshi-redhat** 2019-03-25 13:42 UTC
